export default [
  {
    id: 'car2go.smart',
    name: 'car2go Smart',
    drivingPerMinute: 0.24,
    parkingPerMinute: 0.19,
    includedKilometers: 200,
    extraKilometer: 0.29,
    rentalFee: 0,
    filterProperties: {
      Betreiber: 'car2go',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'car2go.aklasse',
    name: 'car2go A-Klasse',
    drivingPerMinute: 0.31,
    parkingPerMinute: 0.19,
    includedKilometers: 200,
    extraKilometer: 0.29,
    rentalFee: 0,
    filterProperties: {
      Betreiber: 'car2go',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'car2go.clagla',
    name: 'car2go CLA/GLA',
    drivingPerMinute: 0.34,
    parkingPerMinute: 0.19,
    includedKilometers: 200,
    extraKilometer: 0.29,
    rentalFee: 0,
    filterProperties: {
      Betreiber: 'car2go',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'driveNow.mini',
    name: 'DriveNow Mini/BMW 1er',
    drivingPerMinute: 0.31,
    parkingPerMinute: 0.15,
    includedKilometers: 200,
    extraKilometer: 0.29,
    rentalFee: 1,
    filterProperties: {
      Betreiber: 'DriveNow',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'driveNow.minidrivensave',
    name: "DriveNow Mini/BMW 1er Drive'n Save",
    drivingPerMinute: 0.20,
    parkingPerMinute: 0.15,
    includedKilometers: 200,
    extraKilometer: 0.29,
    rentalFee: 1,
    filterProperties: {
      Betreiber: 'DriveNow',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'driveNow.mini3hour',
    name: 'DriveNow Mini 3-Stunden-Paket',
    drivingPerMinute: 0.31,
    parkingPerMinute: 0.15,
    includedKilometers: 200,
    extraKilometer: 0.29,
    rentalFee: 1,
    packagePrice: 29,
    packageBudget: 3 * 60,
    filterProperties: {
      Betreiber: 'DriveNow',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'driveNow.mini6hour',
    name: 'DriveNow Mini 6-Stunden-Paket',
    drivingPerMinute: 0.31,
    parkingPerMinute: 0.15,
    includedKilometers: 200,
    extraKilometer: 0.29,
    rentalFee: 1,
    packagePrice: 54,
    packageBudget: 6 * 60,
    filterProperties: {
      Betreiber: 'DriveNow',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'driveNow.mini9hour',
    name: 'DriveNow Mini 9-Stunden-Paket',
    drivingPerMinute: 0.31,
    parkingPerMinute: 0.15,
    includedKilometers: 200,
    extraKilometer: 0.29,
    rentalFee: 1,
    packagePrice: 79,
    packageBudget: 9 * 60,
    filterProperties: {
      Betreiber: 'DriveNow',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'driveNow.bmw2',
    name: 'DriveNow Mini Cabrio/BMW 2er',
    drivingPerMinute: 0.34,
    parkingPerMinute: 0.15,
    includedKilometers: 200,
    extraKilometer: 0.29,
    rentalFee: 1,
    filterProperties: {
      Betreiber: 'DriveNow',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'driveNow.bmw2drivensave',
    name: "DriveNow Mini Cabrio/BMW 2er Drive'n Save",
    drivingPerMinute: 0.24,
    parkingPerMinute: 0.15,
    includedKilometers: 200,
    extraKilometer: 0.29,
    rentalFee: 1,
    filterProperties: {
      Betreiber: 'DriveNow',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'flinkster.mini',
    name: 'Flinkster "Mini" (Smart, Panda)',
    drivingPerMinute: 2.30 / 60,
    parkingPerMinute: 2.30 / 60,
    includedKilometers: 0,
    extraKilometer: 0.18,
    rentalFee: 0,
    filterProperties: {
      Betreiber: 'Flinkster',
      Verleih: 'Stationär',
    },
  },
  {
    id: 'flinkster.klein',
    name: 'Flinkster "Klein" (Fiesta, Polo)',
    drivingPerMinute: 5.00 / 60,
    parkingPerMinute: 5.00 / 60,
    includedKilometers: 0,
    extraKilometer: 0.18,
    rentalFee: 0,
    filterProperties: {
      Betreiber: 'Flinkster',
      Verleih: 'Stationär',
    },
  },
  {
    id: 'flinkster.kompakt',
    name: 'Flinkster "Kompakt" (Astra, Golf)',
    drivingPerMinute: 6.00 / 60,
    parkingPerMinute: 6.00 / 60,
    includedKilometers: 0,
    extraKilometer: 0.18,
    rentalFee: 0,
    filterProperties: {
      Betreiber: 'Flinkster',
      Verleih: 'Stationär',
    },
  },
  {
    id: 'flinkster.mittel',
    name: 'Flinkster "Mittel" (Passat, Mondeo)',
    drivingPerMinute: 7.00 / 60,
    parkingPerMinute: 7.00 / 60,
    includedKilometers: 0,
    extraKilometer: 0.18,
    rentalFee: 0,
    filterProperties: {
      Betreiber: 'Flinkster',
      Verleih: 'Stationär',
    },
  },
];
