export default [
  {
    id: 'car2go.smart',
    name: 'car2go Smart',
    drivingPerMinute: 0.26,
    parkingPerMinute: 0.26,
    includedKilometers: 200,
    extraKilometer: 0.29,
    rentalFee: 0,
    filterProperties: {
      Betreiber: 'car2go',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'car2go.aklasse',
    name: 'car2go A-Klasse',
    drivingPerMinute: 0.31,
    parkingPerMinute: 0.31,
    includedKilometers: 200,
    extraKilometer: 0.29,
    rentalFee: 0,
    filterProperties: {
      Betreiber: 'car2go',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'car2go.clagla',
    name: 'car2go CLA/GLA',
    drivingPerMinute: 0.34,
    parkingPerMinute: 0.34,
    includedKilometers: 200,
    extraKilometer: 0.29,
    rentalFee: 0,
    filterProperties: {
      Betreiber: 'car2go',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'car2go.smart2hour',
    name: 'car2go Smart 2-Stunden-Paket',
    drivingPerMinute: 0.26,
    parkingPerMinute: 0.26,
    includedKilometers: 80,
    extraKilometer: 0.29,
    rentalFee: 0,
    packagePrice: 17.90,
    packageBudget: 2 * 60,
    filterProperties: {
      Betreiber: 'car2go',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'car2go.smart4hour',
    name: 'car2go Smart 4-Stunden-Paket',
    drivingPerMinute: 0.26,
    parkingPerMinute: 0.26,
    includedKilometers: 120,
    extraKilometer: 0.29,
    rentalFee: 0,
    packagePrice: 29.90,
    packageBudget: 4 * 60,
    filterProperties: {
      Betreiber: 'car2go',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'car2go.smart6hour',
    name: 'car2go Smart 6-Stunden-Paket',
    drivingPerMinute: 0.26,
    parkingPerMinute: 0.26,
    includedKilometers: 160,
    extraKilometer: 0.29,
    rentalFee: 0,
    packagePrice: 44.90,
    packageBudget: 6 * 60,
    filterProperties: {
      Betreiber: 'car2go',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'car2go.smart24hour',
    name: 'car2go Smart 24-Stunden-Paket',
    drivingPerMinute: 0.26,
    parkingPerMinute: 0.26,
    includedKilometers: 200,
    extraKilometer: 0.29,
    rentalFee: 0,
    packagePrice: 79.00,
    packageBudget: 24 * 60,
    filterProperties: {
      Betreiber: 'car2go',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'car2go.aklasse2hour',
    name: 'car2go A-Klasse 2-Stunden-Paket',
    drivingPerMinute: 0.31,
    parkingPerMinute: 0.31,
    includedKilometers: 80,
    extraKilometer: 0.29,
    rentalFee: 0,
    packagePrice: 19.90,
    packageBudget: 2 * 60,
    filterProperties: {
      Betreiber: 'car2go',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'car2go.aklasse4hour',
    name: 'car2go A-Klasse 4-Stunden-Paket',
    drivingPerMinute: 0.31,
    parkingPerMinute: 0.31,
    includedKilometers: 120,
    extraKilometer: 0.29,
    rentalFee: 0,
    packagePrice: 34.90,
    packageBudget: 4 * 60,
    filterProperties: {
      Betreiber: 'car2go',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'car2go.aklasse6hour',
    name: 'car2go A-Klasse 6-Stunden-Paket',
    drivingPerMinute: 0.31,
    parkingPerMinute: 0.31,
    includedKilometers: 160,
    extraKilometer: 0.29,
    rentalFee: 0,
    packagePrice: 49.90,
    packageBudget: 6 * 60,
    filterProperties: {
      Betreiber: 'car2go',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'car2go.aklasse24hour',
    name: 'car2go A-Klasse 24-Stunden-Paket',
    drivingPerMinute: 0.31,
    parkingPerMinute: 0.31,
    includedKilometers: 200,
    extraKilometer: 0.29,
    rentalFee: 0,
    packagePrice: 99.00,
    packageBudget: 24 * 60,
    filterProperties: {
      Betreiber: 'car2go',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'car2go.clagla2hour',
    name: 'car2go CLA/GLA 2-Stunden-Paket',
    drivingPerMinute: 0.34,
    parkingPerMinute: 0.34,
    includedKilometers: 80,
    extraKilometer: 0.29,
    rentalFee: 0,
    packagePrice: 22.90,
    packageBudget: 2 * 60,
    filterProperties: {
      Betreiber: 'car2go',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'car2go.clagla4hour',
    name: 'car2go CLA/GLA 4-Stunden-Paket',
    drivingPerMinute: 0.34,
    parkingPerMinute: 0.34,
    includedKilometers: 120,
    extraKilometer: 0.29,
    rentalFee: 0,
    packagePrice: 38.90,
    packageBudget: 4 * 60,
    filterProperties: {
      Betreiber: 'car2go',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'car2go.clagla6hour',
    name: 'car2go CLA/GLA 6-Stunden-Paket',
    drivingPerMinute: 0.34,
    parkingPerMinute: 0.34,
    includedKilometers: 160,
    extraKilometer: 0.29,
    rentalFee: 0,
    packagePrice: 53.90,
    packageBudget: 6 * 60,
    filterProperties: {
      Betreiber: 'car2go',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'car2go.clagla24hour',
    name: 'car2go CLA/GLA 24-Stunden-Paket',
    drivingPerMinute: 0.34,
    parkingPerMinute: 0.34,
    includedKilometers: 200,
    extraKilometer: 0.29,
    rentalFee: 0,
    packagePrice: 109.00,
    packageBudget: 24 * 60,
    filterProperties: {
      Betreiber: 'car2go',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'driveNow.mini',
    name: 'DriveNow Mini/BMW 1er',
    drivingPerMinute: 0.31,
    parkingPerMinute: 0.31,
    includedKilometers: 200,
    extraKilometer: 0.29,
    rentalFee: 1,
    filterProperties: {
      Betreiber: 'DriveNow',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'driveNow.minidrivensave',
    name: "DriveNow Mini/BMW 1er Drive'n Save",
    drivingPerMinute: 0.20,
    parkingPerMinute: 0.20,
    includedKilometers: 200,
    extraKilometer: 0.29,
    rentalFee: 1,
    filterProperties: {
      Betreiber: 'DriveNow',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'driveNow.mini3hour',
    name: 'DriveNow Mini 3-Stunden-Paket',
    drivingPerMinute: 0.31,
    parkingPerMinute: 0.31,
    includedKilometers: 200,
    extraKilometer: 0.29,
    rentalFee: 1,
    packagePrice: 29,
    packageBudget: 3 * 60,
    filterProperties: {
      Betreiber: 'DriveNow',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'driveNow.mini6hour',
    name: 'DriveNow Mini 6-Stunden-Paket',
    drivingPerMinute: 0.31,
    parkingPerMinute: 0.31,
    includedKilometers: 200,
    extraKilometer: 0.29,
    rentalFee: 1,
    packagePrice: 54,
    packageBudget: 6 * 60,
    filterProperties: {
      Betreiber: 'DriveNow',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'driveNow.mini9hour',
    name: 'DriveNow Mini 9-Stunden-Paket',
    drivingPerMinute: 0.31,
    parkingPerMinute: 0.31,
    includedKilometers: 200,
    extraKilometer: 0.29,
    rentalFee: 1,
    packagePrice: 79,
    packageBudget: 9 * 60,
    filterProperties: {
      Betreiber: 'DriveNow',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'driveNow.bmw2',
    name: 'DriveNow Mini Cabrio/BMW 2er',
    drivingPerMinute: 0.34,
    parkingPerMinute: 0.34,
    includedKilometers: 200,
    extraKilometer: 0.29,
    rentalFee: 1,
    filterProperties: {
      Betreiber: 'DriveNow',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'driveNow.bmw2drivensave',
    name: "DriveNow Mini Cabrio/BMW 2er Drive'n Save",
    drivingPerMinute: 0.24,
    parkingPerMinute: 0.24,
    includedKilometers: 200,
    extraKilometer: 0.29,
    rentalFee: 1,
    filterProperties: {
      Betreiber: 'DriveNow',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'flinkster.mini',
    name: 'Flinkster "Mini" (Smart, Panda)',
    drivingPerMinute: 2.30 / 60,
    parkingPerMinute: 2.30 / 60,
    includedKilometers: 0,
    extraKilometer: 0.18,
    rentalFee: 0,
    filterProperties: {
      Betreiber: 'Flinkster',
      Verleih: 'Stationär',
    },
  },
  {
    id: 'flinkster.klein',
    name: 'Flinkster "Klein" (Fiesta, Polo)',
    drivingPerMinute: 5.00 / 60,
    parkingPerMinute: 5.00 / 60,
    includedKilometers: 0,
    extraKilometer: 0.18,
    rentalFee: 0,
    filterProperties: {
      Betreiber: 'Flinkster',
      Verleih: 'Stationär',
    },
  },
  {
    id: 'flinkster.kompakt',
    name: 'Flinkster "Kompakt" (Astra, Golf)',
    drivingPerMinute: 6.00 / 60,
    parkingPerMinute: 6.00 / 60,
    includedKilometers: 0,
    extraKilometer: 0.18,
    rentalFee: 0,
    filterProperties: {
      Betreiber: 'Flinkster',
      Verleih: 'Stationär',
    },
  },
  {
    id: 'flinkster.mittel',
    name: 'Flinkster "Mittel" (Passat, Mondeo)',
    drivingPerMinute: 7.00 / 60,
    parkingPerMinute: 7.00 / 60,
    includedKilometers: 0,
    extraKilometer: 0.18,
    rentalFee: 0,
    filterProperties: {
      Betreiber: 'Flinkster',
      Verleih: 'Stationär',
    },
  },
  {
    id: 'eddy.scooter',
    name: 'Eddy E-Roller (Zeittarif)',
    drivingPerMinute: 0.19,
    parkingPerMinute: 0.05,
    includedKilometers: 0,
    extraKilometer: 0.0,
    rentalFee: 0,
    filterProperties: {
      Betreiber: 'Eddy',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'eddy.scooter',
    name: 'Eddy E-Roller (Km-Tarif)',
    drivingPerMinute: 0,
    parkingPerMinute: 0.05,
    includedKilometers: 0,
    extraKilometer: 0.59,
    rentalFee: 0,
    filterProperties: {
      Betreiber: 'Eddy',
      Verleih: 'Free Floating',
    },
  },
  {
    id: 'eddy.scooter24hour',
    name: 'Eddy E-Roller 24-Stunden-Tarif',
    drivingPerMinute: 0.19,
    parkingPerMinute: 0.05,
    includedKilometers: 200,
    extraKilometer: 0.29,
    rentalFee: 0,
    packagePrice: 24,
    packageBudget: 24 * 60,
    filterProperties: {
      Betreiber: 'Eddy',
      Verleih: 'Free Floating',
    },
  },
];
